### ISSUE TITLE
Module div to be set programmatically?

### ISSUE THREAD

**Issue by danverde** [byuitechops/byui-canvas-theme#23]
Would it be possible to set the width of each module using css calc? Maybe something like this: 
```css
.moduleItem {
   width: calc(100% - margin / 2);
}
```
